incoming:
  port: 9252
  max-message-length: 1024
outgoing:
  host: <%= ENV['WEB_PORT_3000_TCP_ADDR'] %>
  port: <%= ENV['WEB_PORT_3000_TCP_PORT'] %>
  endpoint: /reports
  username: <%= ENV['UDP_AUTH_USER'] %>
  password: <%= ENV['UDP_AUTH_PASS'] %>
